// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace digeset_server.Core.dtos;

public partial class ConceptoDto
{
    public int ConceptoId { get; set; }

    public string Descripcion { get; set; }

    public decimal Monto { get; set; }

}