// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace digeset_server.Core.dtos;

public partial class UsuarioDto
{
    public int UsuarioId { get; set; }

    public string Nombre { get; set; }

    public string Cedula { get; set; }

    public string Clave { get; set; }
}