// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace digeset_server.Core.entities;

public partial class Concepto
{
    public int ConceptoId { get; set; }

    public string Descripcion { get; set; }

    public double Monto { get; set; }

    public virtual ICollection<Multa> Multa { get; set; } = new List<Multa>();
}