// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using digeset_server.Infrastructure.Context;

#nullable disable

namespace digeset_server.Infrastructure.Migrations
{
    [DbContext(typeof(digesetContext))]
    [Migration("20241208013200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("digeset_server.Core.entities.Agente", b =>
                {
                    b.Property<int>("AgenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgenteId")
                        .HasName("PK__Agente__EA09D85DF09E5DC3");

                    b.ToTable("Agente", (string)null);
                });

            modelBuilder.Entity("digeset_server.Core.entities.Concepto", b =>
                {
                    b.Property<int>("ConceptoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ConceptoId")
                        .HasName("PK__Concepto__BB30F135A80A6E3B");

                    b.ToTable("Concepto", (string)null);
                });

            modelBuilder.Entity("digeset_server.Core.entities.Multa", b =>
                {
                    b.Property<int>("MultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConceptoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("BLOB");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MultaId")
                        .HasName("PK__Multa__DA090DE0F9E588A4");

                    b.HasIndex("AgenteId");

                    b.HasIndex("ConceptoId");

                    b.ToTable("Multa");
                });

            modelBuilder.Entity("digeset_server.Core.entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuario__2B3DE7B84F7C7FC9");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("digeset_server.Core.entities.Multa", b =>
                {
                    b.HasOne("digeset_server.Core.entities.Agente", "Agente")
                        .WithMany("Multa")
                        .HasForeignKey("AgenteId")
                        .IsRequired()
                        .HasConstraintName("FK__Multa__AgenteId__44FF419A");

                    b.HasOne("digeset_server.Core.entities.Concepto", "Concepto")
                        .WithMany("Multa")
                        .HasForeignKey("ConceptoId")
                        .IsRequired()
                        .HasConstraintName("FK__Multa__ConceptoI__4316F928");

                    b.Navigation("Agente");

                    b.Navigation("Concepto");
                });

            modelBuilder.Entity("digeset_server.Core.entities.Agente", b =>
                {
                    b.Navigation("Multa");
                });

            modelBuilder.Entity("digeset_server.Core.entities.Concepto", b =>
                {
                    b.Navigation("Multa");
                });
#pragma warning restore 612, 618
        }
    }
}
